# Generated by Django 6.0 on 2025-12-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
